// Regenerates .design-sync/ds-styles.css — the cssEntry the design-sync converter ships.
// Output = embedded Geist fonts (data-URI) + --font-geist-* vars
//        + Tailwind v4 compiled from src/app/globals.css (tokens + utilities)
//        + a dark-first :root override (the app hardcodes .dark; light is unimplemented).
// Run from the repo root:  node .design-sync/build-styles.mjs
import { readFileSync, writeFileSync, copyFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { resolve } from "node:path";

const repo = process.cwd();
const R = (p) => resolve(repo, p);

// 1. Geist woff2 — shipped inside Next (OFL). Adjust here if a Next upgrade moves them.
const FONT_SANS = R("node_modules/next/dist/next-devtools/server/font/geist-latin.woff2");
const FONT_MONO = R("node_modules/next/dist/next-devtools/server/font/geist-mono-latin.woff2");
for (const f of [FONT_SANS, FONT_MONO]) {
  if (!existsSync(f)) throw new Error(`[build-styles] Geist woff2 not found: ${f} — a Next upgrade may have moved it. Update the path.`);
}
const b64 = (f) => readFileSync(f).toString("base64");

// 2. Tailwind v4 compile of globals.css (scans the repo for used utilities).
execSync(`npx --yes @tailwindcss/cli@4 -i src/app/globals.css -o .design-sync/.cache/tw.css`, {
  cwd: repo,
  stdio: "inherit",
});
const tw = readFileSync(R(".design-sync/.cache/tw.css"), "utf8");

const head = `/* Block 23 Gym DS — Geist fonts (embedded from next/font Geist, OFL) + font vars.
   Prepended to the Tailwind v4 compiled output (tokens + utilities). Generated by build-styles.mjs. */
@font-face{font-family:"Geist";font-style:normal;font-weight:100 900;font-display:swap;src:url(data:font/woff2;base64,${b64(FONT_SANS)}) format("woff2");}
@font-face{font-family:"Geist Mono";font-style:normal;font-weight:100 900;font-display:swap;src:url(data:font/woff2;base64,${b64(FONT_MONO)}) format("woff2");}
:root{--font-geist-sans:"Geist",ui-sans-serif,system-ui,-apple-system,sans-serif;--font-geist-mono:"Geist Mono",ui-monospace,SFMono-Regular,monospace;}
`;

// 3. Dark-first default — promote the .dark token values (DESIGN-SYSTEM §3.2/§3.3/§3.5 dark column)
//    to :root so the DS canvas + every preview card render in the brand's default theme.
const darkDefault = `
/* ── Dark-first default (app ships .dark on <html>; light is unimplemented). ── */
:root {
  --background: #0f172a; --foreground: #f1f5f9;
  --card: #15203a; --card-foreground: #f1f5f9;
  --popover: #1e293b; --popover-foreground: #f1f5f9;
  --primary: #6366f1; --primary-foreground: #ffffff;
  --secondary: #1e293b; --secondary-foreground: #e2e8f0;
  --muted: #1e293b; --muted-foreground: #94a3b8;
  --accent: #27344c; --accent-foreground: #f1f5f9;
  --destructive: #dc2626; --destructive-foreground: #ffffff;
  --border: #283449; --input: #334155; --ring: #818cf8;
  --success: #059669; --success-foreground: #ffffff;
  --warning: #d97706; --warning-foreground: #ffffff;
  --info: #0284c7; --info-foreground: #ffffff;
  --at-risk: #f97316; --at-risk-foreground: #ffffff;
  --success-on: #34d399; --warning-on: #fbbf24; --danger-on: #f87171;
  --info-on: #38bdf8; --primary-on: #818cf8;
  --chart-1: #818cf8; --chart-2: #34d399; --chart-3: #fbbf24;
  --chart-4: #38bdf8; --chart-5: #f472b6; --chart-6: #a3e635;
  --sidebar: #15203a; --sidebar-foreground: #f1f5f9;
  --sidebar-primary: #6366f1; --sidebar-primary-foreground: #ffffff;
  --sidebar-accent: #27344c; --sidebar-accent-foreground: #f1f5f9;
  --sidebar-border: #283449; --sidebar-ring: #818cf8;
}
body {
  background: var(--background);
  color: var(--foreground);
  font-family: var(--font-geist-sans, ui-sans-serif, system-ui, sans-serif);
}
`;

writeFileSync(R(".design-sync/ds-styles.css"), head + "\n" + tw + darkDefault);
// pkgroot is where the converter reads cssEntry from (bounded to PKG_DIR).
if (existsSync(R(".design-sync/pkgroot"))) copyFileSync(R(".design-sync/ds-styles.css"), R(".design-sync/pkgroot/ds-styles.css"));
console.log("[build-styles] wrote .design-sync/ds-styles.css");
